server:
  port: 8005
spring:
  datasource:
    url: jdbc:mysql://49.235.82.50:3306/daole_cloud?useUnicode=true&characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Madp123!@#
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4FrfnCYueTBdnhJADQ2y
      keysecret: NRzMULHw6zhD0WWcYNxPMOlEYrF6RF
      bucketname: daole-oss
      filehost: ueditor