server:
  port: 8006
spring:
  datasource:
    url: jdbc:mysql://49.235.82.50:3306/daole_cloud?useUnicode=true&characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
